package org.desafio.app.utils.exceptions;


public class ClientNotFoundException extends RuntimeException {

    public ClientNotFoundException() {
        super("Cliente n√£o encontrado na base de dados");
    }
}
